# Generated by Django 4.0.2 on 2022-03-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mentee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='strengthweakness',
            name='sw_type',
            field=models.TextField(unique=True),
        ),
    ]
