# Generated by Django 4.0.2 on 2022-03-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_profile_mentee_alter_notification_is_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.strengthweakness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeaknessList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.strengthweakness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StrengthWeaknessList',
        ),
    ]
