# Generated by Django 4.0.2 on 2022-03-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_meetingweaknesses_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingproposal',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
    ]
