# Generated by Django 4.0.2 on 2022-03-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_meetingproposal_rejection_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalfeedback',
            name='creation_datetime',
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ImprovedWeaknesses',
        ),
    ]
