# Generated by Django 4.0.2 on 2022-03-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_generalfeedback_creation_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalfeedback',
            name='negatives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='positives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupeventfeedback',
            name='negatives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupeventfeedback',
            name='positives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingfeedback',
            name='negatives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingfeedback',
            name='positives',
            field=models.TextField(blank=True),
        ),
    ]
