# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main, backend ]
  pull_request:
    branches: [ main, backend ]

jobs:
  test-backend:

    runs-on: ubuntu-20.04 # Comes with postgresql installed!

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres createuser -s mentorprise
        sudo -u postgres psql -c "ALTER USER mentorprise PASSWORD '12345';"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
        cd mentorprise/backend_dev/
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Error check all code with flake8
      run: |
        cd mentorprise/backend_dev/
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Lint main source file with pylint
      run: |
        cd mentorprise/backend_dev/
        pylint . --fail-under=0
    - name: Run Tests
      env:
        DB: mentorprise
        DB_USER: mentorprise
        DB_PASSWORD: 12345
      run: |
        cd mentorprise/backend_dev/mentorprise
        coverage run --source='.' manage.py test
        coverage xml --omit=app/views.py
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
