# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main, backend ]
  pull_request:
    branches: [ main, backend ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
    - name: Error check all code with flake8
      run: |
        flake8 mentorprise/backend_dev/ --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Lint main source file with pylint
      run: |
        pylint mentorprise/backend_dev/* --fail-under=0 --rcfile=mentorprise/backend_dev/.pylintrc
